export const expenseCategories = [
    {
        id:'food',
        display:'Food'
    },
    {
        id:'accommodation',
        display:'Accommodation'
    },
    {
        id:'activities',
        display:'activities'
    },
    {
        id:'shoping',
        display:'Shoping'
    },{
        id:'other',
        display:'Other'
    }
]